---
title: "Download raw data to repository"
output: pdf_document
---

This script downloads data from a specific folder on our Google Drive

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googledrive)
library(here)
library(tidyverse)


## Sets R not to use scientific notations
options(scipen=999) 

# Create raw data folders 
dir.create(here::here("raw_data"))

```

## Download data files into local computer

Make sure the file path on the code is updated to the correct folder.

```{r download files}
# url of folder where the data lives
# Copy paste the url of the folder where the data lives

folder_url <- "https://drive.google.com/drive/folders/1aAVaoQOBinW7n-01RIBSq_AFbKdthAqJ"

# list of files inside the folder
files <- drive_ls(as_id(folder_url))


## Download all file to local computer. 

purrr::walk2(
    map(files$id, as_id),
    paste0("raw_data/", files$name),
    drive_download,
    overwrite = TRUE)

```

## Check all files were downloaded

```{r}
## File path to raw data used in this script
raw_data_path <- here::here("raw_data")

# Count files inside the raw_data folder to make sure the number of files downloaded is what is expected.
length(list.files(raw_data_path))

```
